---
enable_dotfiles: yes
enable_homebrew: yes
enable_mas: yes
enable_macos_defaults: yes

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_installed_packages:
  - mas
  - starship
  - shellcheck
  - wget
  - lsusb
  - gnupg
  - pinentry-mac
  - zsh
  - antigen
  - mosh
  - fzf
  - bat
  - httpie
  - tldr
  - exa
  - ripgrep
  - nvm
  - direnv
  - coreutils # For g-prefixed Linux-like binaries

homebrew_cask_apps:
  - font-fira-code-nerd-font
  - google-chrome
  - visual-studio-code
  - 1password
  - iterm2
  - balenaetcher
  - slack
  - spotify
  - notion
  - keka
  - vlc
  - postman
  - nordvpn
  - prefs-editor
  - tomighty
  - kap
  - stack-stack
  - swish
  - calibre
  - mutesync

mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1176895641, name: "Spark" }
  - { id: 1355679052, name: "Dropover" }
# assume we're already logged in
mas_email: ""
mas_password: ""

dotfiles:
  - { dest: "~/.zshrc", src: "{{ playbook_dir }}/dotfiles/.zshrc" }
  - { dest: "~/.zsh_functions", src: "{{ playbook_dir }}/dotfiles/.zsh_functions" }
  - { dest: "~/.ssh", src: "{{ playbook_dir }}/dotfiles/.ssh" }
  - { dest: "~/.gnupg", src: "{{ playbook_dir }}/dotfiles/.gnupg" }
  - { dest: "~/.gitconfig", src: "{{ playbook_dir }}/dotfiles/.gitconfig" }
  - { dest: "~/.gitignore_global", src: "{{ playbook_dir }}/dotfiles/.gitignore_global" }
  - { dest: "~/.profile", src: "{{ playbook_dir }}/dotfiles/.profile" }
  - { dest: "~/.config/starship.toml", src: "{{ playbook_dir }}/dotfiles/.config/starship.toml" }

  - { dest: "~/.ssh/id_rsa", src: "{{ playbook_dir }}/secrets/id_rsa" }
