#!/usr/bin/env bash

set -euo pipefail

only_macos() {
  if [[ $OSTYPE != 'darwin'* ]]; then
    exit
  fi
}

add_ssh_key() {
  SSH_AUTH_SOCK=${APPLE_DEFAULT_SSH_AUTH_SOCK:-$SSH_AUTH_SOCK} ssh-add --apple-use-keychain ~/.ssh/id_rsa
}

only_macos
add_ssh_key
