#!/usr/bin/env bash

set -euo pipefail

only_macos() {
  if [[ $OSTYPE != 'darwin'* ]]; then
    echo "Not on macOS, skipping"
    exit
  fi
}

add_ssh_key() {
  echo "FIXME"
  # ssh-add --apple-use-keychain ~/.ssh/id_rsa
}

only_macos
add_ssh_key
