#!/usr/bin/env bash

set -euo pipefail

install_homebrew() {
  if ! command -v brew &> /dev/null; then
    echo "Installing homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
}

brew_install() {
  brew bundle --file=- <<EOF
tap "hashicorp/tap"

brew "git"
brew "age"
brew "starship"
brew "shellcheck"
brew "diff-so-fancy"
brew "wget"
brew "lsusb"
brew "zsh"
brew "antidote"
brew "mosh"
brew "fzf"
brew "bat"
brew "httpie"
brew "tldr"
brew "ripgrep"
brew "fnm"
brew "direnv"
brew "coreutils"
brew "ffmpeg"
brew "zoxide"
brew "hadolint"
brew "cloudflared"
brew "fwupd"
brew "hashicorp/tap/terraform"
brew "kubernetes-cli"
brew "hyperfine"

cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "visual-studio-code"
cask "1password"
cask "iterm2"
cask "balenaetcher"
cask "slack"
cask "spotify"
cask "keka"
cask "iina"
cask "postman"
cask "prefs-editor"
cask "tomighty"
cask "kap"
cask "swish"
cask "calibre"
cask "lunar"
cask "bartender"
cask "shottr"
cask "arc"
cask "orbstack"

mas "Amphetamine", id: 937984704
mas "Spark Desktop", id: 6445813049
mas "Dropover", id: 1355679052
mas "Dato", id: 1470584107
mas "CleanMyKeyboard", id: 6468120888
EOF
}

linux_install() {
  sudo apt-get install -y git zsh shellcheck fzf
  # Install starship
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
  # Install antidote
  git clone --depth=1 https://github.com/mattmc3/antidote.git "${ZDOTDIR:-~}/.antidote"
  # Install zoxide
  curl -sS https://webinstall.dev/zoxide | bash
}

install() {
  if [[ $OSTYPE == 'darwin'* ]]; then
    install_homebrew
    brew_install
  else
    linux_install
  fi
}

install
