#!/usr/bin/env bash

set -euo pipefail

only_macos() {
  if [[ $OSTYPE != 'darwin'* ]]; then
    echo "Not on macOS, skipping"
    exit
  fi
}

add_ssh_key() {
  ssh-add --apple-use-keychain ~/.ssh/id_rsa
  ssh-add --apple-use-keychain ~/.ssh/id_ed25519
}

only_macos
add_ssh_key
