#!/usr/bin/env bash

set -euo pipefail

only_macos() {
  if [[ $OSTYPE != 'darwin'* ]]; then
    echo "Not on macOS, skipping"
    exit
  fi
}

close_settings() {
  osascript -e 'tell application "System Preferences" to quit'
}

set_defaults() {
  echo "Setting Dock defaults..."
  # Disable magnification
  defaults write com.apple.dock magnification -bool false
  # Set tile size
  defaults write com.apple.dock tilesize -int 64
  # Set dock position
  defaults write com.apple.dock orientation -string "bottom"
  # Change minimize/maximize window effect
  defaults write com.apple.dock mineffect -string "scale"
  # Minimize windows into their application’s icon
  defaults write com.apple.dock minimize-to-application -bool true
  # Enable launch animation
  defaults write com.apple.dock launchanim -bool true
  # Automatically hide and show the Dock
  defaults write com.apple.dock autohide -bool true
  # Set the autohide delay to 0
  defaults write com.apple.dock autohide-delay -float 0
  # Show indicator lights for open applications in the Dock
  defaults write com.apple.dock show-process-indicators -bool true
  # Don’t show recent applications in Dock
  defaults write com.apple.dock show-recents -bool false
  # Make keyboard more reactive
  defaults write NSGlobalDomain InitialKeyRepeat -int 15
  defaults write NSGlobalDomain KeyRepeat -int 2

  # Finder
  defaults write "com.apple.finder" "ShowExternalHardDrivesOnDesktop" '0'
  defaults write "com.apple.finder" "ShowRemovableMediaOnDesktop" '0'
  defaults write "com.apple.finder" "FXPreferredViewStyle" 'Nlsv'
  defaults write "com.apple.finder" "ShowPathbar" '1'
  defaults write "com.apple.finder" "NSToolbar Configuration Browser" '{"TB Default Item Identifiers"=("com.apple.finder.BACK","com.apple.finder.SWCH",NSToolbarSpaceItem,"com.apple.finder.ARNG","com.apple.finder.SHAR","com.apple.finder.LABL","com.apple.finder.ACTN",NSToolbarSpaceItem,"com.apple.finder.SRCH",);"TB Display Mode"=2;"TB Icon Size Mode"=1;"TB Is Shown"=1;"TB Item Identifiers"=("com.apple.finder.BACK","com.apple.finder.SWCH",NSToolbarSpaceItem,"com.apple.finder.SHAR",NSToolbarSpaceItem,"com.apple.finder.SRCH",);"TB Size Mode"=1;}'
  defaults write "com.apple.finder" "FXDefaultSearchScope" 'SCcf'
  defaults write "com.apple.finder" "NewWindowTarget" 'PfHm'

  defaults write "Apple Global Domain" "AppleShowAllExtensions" '1'

  # Menubar
  defaults delete "com.apple.Spotlight" "NSStatusItem Visible Item-0" || true
  defaults write "com.apple.menuextra.clock" "ShowDayOfWeek" '0'

  # Trackpad
  defaults write "Apple Global Domain" "com.apple.trackpad.scaling" '"1.5"'
  defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerDrag" '1'
  defaults write "com.apple.driver.AppleBluetoothMultitouch.trackpad" "TrackpadThreeFingerDrag" '1'
}

enable_sudo_touch_id() {
  sed -e 's/^#auth/auth/' /etc/pam.d/sudo_local.template | sudo tee /etc/pam.d/sudo_local
}

restart_apps() {
  killall Dock
}

only_macos
close_settings
set_defaults
enable_sudo_touch_id
restart_apps
