---
- name: Create ~/.config directory
  file:
    path: "~/.config"
    state: directory
    mode: '700'

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ dotfiles }}"
