---
###
# Dock
###

- name: Set dock settings
  osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    # Disable magnification
    - { key: "magnification", type: "bool", value: false }
    # Set tile size
    - { key: "tilesize", type: "float", value: 64 }
    # Set dock position
    - { key: "orientation", type: "string", value: "bottom" }
    # Change minimize/maximize window effect
    - { key: "mineffect", type: "string", value: "scale" }
    # Minimize windows into their application’s icon
    - { key: "minimize-to-application", type: "bool", value: true }
    # Enable launch animation
    - { key: "launchanim", type: "bool", value: true }
    # Automatically hide and show the Dock
    - { key: "autohide", type: "bool", value: true }
    # Set the autohide delay to 0
    - { key: "autohide-delay", type: "float", value: 0 }
    # Show indicator lights for open applications in the Dock
    - { key: "show-process-indicators", type: "bool", value: true }
    # Don’t show recent applications in Dock
    - { key: "show-recents", type: "bool", value: false }
  notify:
    - Kill Dock
