---
###
# Dock
###

- name: Set dock settings
  osx_defaults:
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    # Disable magnification
    - { key: "magnification", type: "bool", value: false }
    # Set tile size
    - { key: "tilesize", type: "float", value: 64 }
    # Set dock position
    - { key: "orientation", type: "string", value: "bottom" }
    # Change minimize/maximize window effect
    - { key: "mineffect", type: "string", value: "scale" }
    # Minimize windows into their application’s icon
    - { key: "minimize-to-application", type: "bool", value: true }
    # Enable launch animation
    - { key: "launchanim", type: "bool", value: true }
    # Automatically hide and show the Dock
    - { key: "autohide", type: "bool", value: true }
    # Set the autohide delay to 0
    - { key: "autohide-delay", type: "float", value: 0 }
    # Show indicator lights for open applications in the Dock
    - { key: "show-process-indicators", type: "bool", value: true }
    # Don’t show recent applications in Dock
    - { key: "show-recents", type: "bool", value: false }
  notify:
    - Kill Dock

###
# Bar
###

- name: Show battery percentage
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"
  notify:
    - Kill Finder

- name: Show expected menu items
  osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    value:
      - /System/Library/CoreServices/Menu Extras/Clock.menu
      - /System/Library/CoreServices/Menu Extras/Battery.menu
      - /System/Library/CoreServices/Menu Extras/AirPort.menu
      - /System/Library/CoreServices/Menu Extras/Bluetooth.menu
      - /System/Library/CoreServices/Menu Extras/Volume.menu
  notify:
    - Kill Finder

- name: Show volume menu
  osx_defaults:
    domain: com.apple.systemuiserver
    key: NSStatusItem Visible com.apple.menuextra.volume
    type: bool
    value: true
  notify:
    - Kill Finder

- name: Show / hide items in the menu
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible {{ item.item }}"
    type: "bool"
    value: "{{ item.visible }}"
  with_items:
    # Wi-Fi
    - { item: "com.apple.menuextra.airport", visible: true }
    # Battery
    - { item: "com.apple.menuextra.battery", visible: true }
    # Bluetooth
    - { item: "com.apple.menuextra.bluetooth", visible: true }
    # Clock
    - { item: "com.apple.menuextra.clock", visible: true }
    # Volume
    - { item: "com.apple.menuextra.volume", visible: true }
    # Siri
    - { item: "Siri", visible: false }
  notify:
    - Kill Finder
