---
- name: Check if homebrew fish is installed
  stat: { path: "/usr/local/bin/fish" }
  register: brew_fish

- name: Add homebrew fish to /etc/shells
  lineinfile: { dest: "/etc/shells", line: "/usr/local/bin/fish", state: "present"}
  when: brew_fish.stat.exists

- name: Set default shell to fish
  user: { name: "{{ ansible_user_id }}", shell: "/usr/local/bin/fish" }
  when: brew_fish.stat.exists
