---
- name: Check if homebrew zsh is installed
  stat: { path: "/usr/local/bin/zsh" }
  register: brew_zsh

- name: Add homebrew zsh to /etc/shells
  lineinfile: { dest: "/etc/shells", line: "/usr/local/bin/zsh", state: "present"}
  become: yes
  when: brew_zsh.stat.exists

- name: Set default shell to brew zsh
  user: { name: "{{ ansible_user_id }}", shell: "/usr/local/bin/zsh" }
  become: yes
  when: brew_zsh.stat.exists
