#!/usr/bin/env bash

export HOMEBREW_NO_ANALYTICS=1

# Global
export PATH="$(brew --prefix)/sbin:$PATH"

# SSH
export APPLE_DEFAULT_SSH_AUTH_SOCK="$SSH_AUTH_SOCK"
export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Go
export GOPATH="${HOME}/Dev/go" 

# NVM start
export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh"  # This loads nvm
[ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && . "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
# NVM end
