#!/usr/bin/env bash

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

if [[ $OSTYPE == 'darwin'* ]]; then
  # Homebrew
  export HOMEBREW_NO_ANALYTICS=1
  export PATH="$(brew --prefix)/sbin:$PATH"

  # Fix mosh, see http://pesin.space/posts/2020-10-05-mosh-macos/
  export LANG=en_US.UTF-8
  export LC_CTYPE=en_US.UTF-8
fi
