#!/usr/bin/env zsh

if [[ $OSTYPE == 'darwin'* ]]; then
  # Homebrew
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

fpath+=~/.zsh_functions
autoload copy disable_gatekeeper github_clone pretty_log \
time_machine_exclude_deps update switch_eject switch_split \
download_youtube_mp3 plist_diff update_dock

# Needed for Oh-My-Zsh plugins
export ZSH_CACHE_DIR="$HOME/.cache"
mkdir -p "$ZSH_CACHE_DIR/completions"
autoload -Uz compinit && compinit

# Antidote

if [[ $OSTYPE == 'darwin'* ]]; then
  # Use antidote from homebrew
  source $(brew --prefix)/share/antidote/antidote.zsh
else
  source "${ZDOTDIR:-~}/.antidote/antidote.zsh"
fi

antidote load

# Setup history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Start fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
# End fix slowness of pastes

# Source ~/.profile if it exists
if test -e "$HOME/.profile"; then
  source "$HOME/.profile"
fi

# Source ~/.profile_override if it exists
# .profile_override is not tracked in git
if test -e "$HOME/.profile_override"; then
  source "$HOME/.profile_override"
fi

# Init starship
eval "$(starship init zsh)"

# Init fnm
eval "$(fnm env --use-on-cd)"
